"""Well-known network/compute vendors and models for capture dropdowns."""

from __future__ import annotations

DEVICE_TYPES = [
    "server",
    "switch",
    "router",
    "firewall",
    "storage",
    "pdu",
    "ups",
    "other",
]

FAN_ORIENTATIONS = [
    {"id": "front-intake", "label": "Front intake (correct cold aisle)"},
    {"id": "rear-intake", "label": "Rear intake"},
    {"id": "incorrect-hot-aisle", "label": "Incorrect — hot aisle"},
    {"id": "incorrect-cold-aisle", "label": "Incorrect — cold aisle"},
    {"id": "unknown", "label": "Unknown / not visible"},
]

VENDORS: dict[str, list[str]] = {
    "Cisco": [
        "Catalyst 9200",
        "Catalyst 9300",
        "Catalyst 9300-48P",
        "Catalyst 9400",
        "Catalyst 9500",
        "Nexus 93180YC-EX",
        "Nexus 9336C-FX2",
        "Nexus 9504",
        "ISR 4331",
        "ISR 4451",
        "ASR 1001-X",
        "ASR 1002-HX",
        "ASA 5516-X",
        "Firepower 1120",
        "Firepower 2130",
        "UCS C220 M6",
        "UCS C240 M6",
        "UCS C240 M7",
        "CIMC",
        "Other",
    ],
    "Juniper": [
        "EX4300",
        "EX4400",
        "QFX5120",
        "QFX5130",
        "MX204",
        "MX480",
        "SRX345",
        "SRX1500",
        "PTX1000",
        "Other",
    ],
    "Arista": [
        "DCS-7050SX3-48YC8",
        "DCS-7060CX-32S",
        "DCS-7280R3",
        "DCS-7300X3",
        "DCS-7170",
        "Other",
    ],
    "MikroTik": [
        "CCR2004-1G-12S+2XS",
        "CCR2216-1G-12XS-2XQ",
        "CRS326-24G-2S+",
        "CRS317-1G-16S+",
        "RB4011iGS+",
        "RB5009UG+S+",
        "hEX S",
        "Other",
    ],
    "TRENDnet": [
        "TEG-S80g",
        "TEG-S16g",
        "TI-PG80",
        "TPE-TG80g",
        "TPE-TG160g",
        "Other",
    ],
    "Dell": [
        "PowerEdge R650",
        "PowerEdge R750",
        "PowerEdge R760",
        "PowerEdge R660",
        "PowerEdge MX740c",
        "PowerSwitch S5248F-ON",
        "PowerSwitch N3248TE-ON",
        "PowerVault ME5024",
        "Other",
    ],
    "HPE Aruba": [
        "Aruba 2930F",
        "Aruba 3810M",
        "Aruba 6300M",
        "Aruba 8360",
        "Aruba CX 8325",
        "ProLiant DL360 Gen10",
        "ProLiant DL380 Gen10",
        "ProLiant DL360 Gen11",
        "ProLiant DL380 Gen11",
        "Other",
    ],
    "Fortinet": [
        "FortiGate 60F",
        "FortiGate 100F",
        "FortiGate 200F",
        "FortiGate 600F",
        "FortiGate 1800F",
        "FortiSwitch 148F",
        "FortiSwitch 1024E",
        "FortiAnalyzer 800F",
        "Other",
    ],
    "Ubiquiti": [
        "UniFi Switch Pro 24",
        "UniFi Switch Pro 48 PoE",
        "UniFi Aggregation",
        "UniFi Dream Machine Pro",
        "UniFi Dream Machine SE",
        "EdgeRouter 4",
        "EdgeSwitch 24",
        "Other",
    ],
    "Netgear": [
        "M4250-26G4F-PoE+",
        "M4300-24X24F",
        "GS724T",
        "GS748T",
        "XS728T",
        "Other",
    ],
    "Palo Alto Networks": [
        "PA-440",
        "PA-850",
        "PA-1410",
        "PA-3220",
        "PA-3410",
        "PA-5220",
        "Other",
    ],
    "Supermicro": [
        "SuperServer 1029U",
        "SuperServer 2029P",
        "SuperServer SYS-221H-TNR",
        "Other",
    ],
    "Lenovo": [
        "ThinkSystem SR630",
        "ThinkSystem SR650",
        "ThinkSystem SR650 V3",
        "Other",
    ],
    "NVIDIA": [
        "SN3700",
        "SN4700",
        "SN5600",
        "Other",
    ],
    "APC": [
        "AP7921",
        "AP8941",
        "AP8881",
        "SRT5KRMXLT",
        "SMX3000RMLV2U",
        "Other",
    ],
    "Eaton": [
        "9PX 3000",
        "9PX 5000",
        "ePDU G3",
        "Other",
    ],
    "Raritan": [
        "PX3-5466V",
        "PX3-5880V",
        "Other",
    ],
    "F5": [
        "BIG-IP i2800",
        "BIG-IP rSeries r10900",
        "Other",
    ],
    "Check Point": [
        "6200",
        "16000",
        "28000",
        "Other",
    ],
    "Ciena": [
        "5164",
        "5171",
        "6500",
        "Other",
    ],
    "CommScope": [
        "SYSTIMAX 360",
        "imVision",
        "Other",
    ],
    "IBM": [
        "Power S1022",
        "FlashSystem 5200",
        "Other",
    ],
    "Oracle": [
        "X9-2",
        "ZFS Storage ZS9-2",
        "Other",
    ],
    "Other": ["Other"],
}

RACK_HEIGHT_PRESETS = [42, 45, 47, 48, 52, 58]


def catalog_payload() -> dict:
    return {
        "device_types": DEVICE_TYPES,
        "fan_orientations": FAN_ORIENTATIONS,
        "vendors": [{"name": name, "models": models} for name, models in VENDORS.items()],
        "rack_height_presets": RACK_HEIGHT_PRESETS,
        "other_label": "Other",
    }
